# Form implementation generated from reading ui file 'f:\Python2024\Projects\PyQT_Project\HW.41\simple_login.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setEnabled(True)
        Form.resize(401, 251)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        Form.setFont(font)
        self.login_label = QtWidgets.QLabel(parent=Form)
        self.login_label.setGeometry(QtCore.QRect(80, 20, 251, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.login_label.setFont(font)
        self.login_label.setTextFormat(QtCore.Qt.TextFormat.RichText)
        self.login_label.setScaledContents(False)
        self.login_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.login_label.setWordWrap(False)
        self.login_label.setIndent(1)
        self.login_label.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.LinksAccessibleByMouse)
        self.login_label.setObjectName("login_label")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(110, 90, 251, 101))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.username_btn = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.username_btn.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhNone)
        self.username_btn.setText("")
        self.username_btn.setCheckable(False)
        self.username_btn.setDefault(False)
        self.username_btn.setFlat(False)
        self.username_btn.setObjectName("username_btn")
        self.verticalLayout.addWidget(self.username_btn)
        self.password_btn = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.password_btn.setAcceptDrops(False)
        self.password_btn.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhDialableCharactersOnly|QtCore.Qt.InputMethodHint.ImhDigitsOnly|QtCore.Qt.InputMethodHint.ImhFormattedNumbersOnly|QtCore.Qt.InputMethodHint.ImhLowercaseOnly|QtCore.Qt.InputMethodHint.ImhUppercaseOnly)
        self.password_btn.setText("")
        self.password_btn.setAutoDefault(True)
        self.password_btn.setDefault(False)
        self.password_btn.setObjectName("password_btn")
        self.verticalLayout.addWidget(self.password_btn)
        self.User_name_label = QtWidgets.QLabel(parent=Form)
        self.User_name_label.setGeometry(QtCore.QRect(10, 110, 71, 16))
        self.User_name_label.setObjectName("User_name_label")
        self.password_label = QtWidgets.QLabel(parent=Form)
        self.password_label.setGeometry(QtCore.QRect(20, 160, 71, 16))
        self.password_label.setObjectName("password_label")
        self.Submit_btn = QtWidgets.QPushButton(parent=Form)
        self.Submit_btn.setGeometry(QtCore.QRect(260, 210, 86, 26))
        self.Submit_btn.setDefault(True)
        self.Submit_btn.setObjectName("Submit_btn")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.login_label.setText(_translate("Form", "SIMPLE LOGIN FORM "))
        self.User_name_label.setText(_translate("Form", "User Name:"))
        self.password_label.setText(_translate("Form", "Password:"))
        self.Submit_btn.setText(_translate("Form", "Submit"))
